version: '3.8'  # or your desired version

volumes:
  mongodb_data_container:
    driver: local

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: kuberkeluh
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    
  web:
    build: ../.
    ports:
      - 3000:3000
    depends_on:
      - mongodb_container
    environment:
      MONGO_URI: mongodb://root:admin123@localhost:27017/kuberkeluh


