version: '3.8'  # or your desired version

volumes:
  mongodb_data_container:
    driver: local

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: kuberkeluh
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    
  web:
    build:
      context: ..
      dockerfile: web.dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb_container

  # server:
  #   build:
  #     context: ..
  #     dockerfile: server.dockerfile
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - mongodb_container
  #   environment:
  #     MONGODB_URI: mongodb://root:admin123@mongodb_container:27017/kuberkeluh
  #     PORT: 3001

