version: '3.8'  # or your desired version

volumes:
  mongodb_data_container:
    driver: local

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: kuberkeluh
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

